### auth.http
@baseUrl = http://localhost:3000
@token = 

###deliveries without authentication
GET {{baseUrl}}/deliveries/public

###deliveries with authentication
GET {{baseUrl}}/deliveries
Authorization: Bearer {{token}}

###deliveries by id without authentication
GET {{baseUrl}}/deliveries/public/2

###deliveries by id with authentication
GET {{baseUrl}}/deliveries/1
Authorization: Bearer {{token}}

###deliveries create without authentication
POST {{baseUrl}}/deliveries/public
Content-Type: application/json

{
  "order_id": 5,
  "date": "2025-10-16",
  "status": "ACTIVE",
  "observations": "Entrega urgente"
}

###deliveries create with authentication
POST {{baseUrl}}/deliveries
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "order_id": 1,
  "date": "2025-10-15",
  "status": "ACTIVE",
  "observations": "Entrega urgente"
}
###deliveries update without authentication
PATCH {{baseUrl}}/deliveries/public/5
Content-Type: application/json

{
  "observations": "Entrega normal"
}

###deliveries update with authentication
PATCH {{baseUrl}}/deliveries/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "observations": "Entrega normal"
}
###deliveries delete without authentication
DELETE {{baseUrl}}/deliveries/public/5
###deliveries delete with authentication
DELETE {{baseUrl}}/deliveries/1
Authorization: Bearer {{token}}

###deliveries logical delete without authentication
DELETE {{baseUrl}}/deliveries/public/7/logic
###deliveries logical delete with authentication
DELETE {{baseUrl}}/deliveries/2/logic
Authorization: Bearer {{token}}