@baseUrl = http://localhost:3000
@token = 
### GET all frames (sin autorización)
GET {{baseUrl}}/frames/public

### GET all frames (con autorización)
GET {{baseUrl}}/frames
Authorization: Bearer {{token}}

### GET frame by ID (sin autorización)
GET {{ baseUrl}}/frames/public/2

### GET frame by ID (con autorización)
GET {{baseUrl}}/frames/1
Authorization: Bearer {{token}}

### CREATE frame (sin autorización)
POST {{baseUrl}}/frames/public
Content-Type: application/json

{
  "brand": "RayBan",
  "model": "RB124",
  "material": "metal",
  "color": "black",
  "price": 500,
  "stock": 5,
  "supplier_id": 1,
  "image": "frame.jpg",
  "status": "ACTIVE"
}

### CREATE frame (con autorización)
POST {{baseUrl}}/frames
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "brand": "RayBan",
  "model": "RB123",
  "material": "metal",
  "color": "black",
  "price": 200,
  "stock": 5,
  "supplier_id": 1,
  "image": "frame.jpg",
  "status": "ACTIVE"
}

### UPDATE frame (sin autorización)
PATCH {{baseUrl}}/frames/public/5
Content-Type: application/json

{
  "price": 220,
  "stock": 7
}

### UPDATE frame (con autorización)
PATCH {{baseUrl}}/frames/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 220,
  "stock": 7
}

### DELETE frame físico (sin autorización)
DELETE {{baseUrl}}/frames/public/6

### DELETE frame físico (con autorización)
DELETE {{baseUrl}}/frames/1
Authorization: Bearer {{token}}

### DELETE frame lógico (sin autorización)
DELETE {{baseUrl}}/frames/public/5/logic

### DELETE frame lógico (con autorización)
DELETE {{baseUrl}}/frames/1/logic
Authorization: Bearer {{token}}