@baseUrl = http://localhost:3000
@token = 
### GET all lenses (sin autorización)
GET {{baseUrl}}/lenses/public

### GET all lenses (con autorización)
GET {{baseUrl}}/lenses
Authorization: Bearer {{token}}

### GET lens by ID (sin autorización)
GET {{baseUrl}}/lenses/public/1

### GET lens by ID (con autorización)
GET {{baseUrl}}/lenses/1
Authorization: Bearer {{token}}

### CREATE lens (sin autorización)
POST {{baseUrl}}/lenses/public
Content-Type: application/json

{
  "image": "url.jpg",
  "type": "monofocal",
  "material": "acrylic",
  "treatment": "anti-reflective",
  "price": 500,
  "stock": 10,
  "supplier_id": 1,
  "status": "ACTIVE"
}

### CREATE lens (con autorización)
POST {{baseUrl}}/lenses
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "image": "url.jpg",
  "type": "monofocal",
  "material": "acrylic",
  "treatment": "anti-reflective",
  "price": 100,
  "stock": 10,
  "supplier_id": 1,
  "status": "ACTIVE"
}

### UPDATE lens (sin autorización)
PATCH {{baseUrl}}/lenses/public/101
Content-Type: application/json

{
  "price": 120,
  "stock": 15
}

### UPDATE lens (con autorización)
PATCH {{baseUrl}}/lenses/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 120,
  "stock": 15
}

### DELETE lens físico (sin autorización)
DELETE {{baseUrl}}/lenses/public/5

### DELETE lens físico (con autorización)
DELETE {{baseUrl}}/lenses/1
Authorization: Bearer {{token}}

### DELETE lens lógico (sin autorización)
DELETE {{baseUrl}}/lenses/public/10/logic

### DELETE lens lógico (con autorización)
DELETE {{baseUrl}}/lenses/1/logic
Authorization: Bearer {{token}}