@baseUrl = http://localhost:3000
@token = 
GET {{baseUrl}}/orders/public
###
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/orders/public/1
###
GET {{baseUrl}}/orders/1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/orders/public
Content-Type: application/json

{
  "patient_id": 1,
  "date": "2025-10-15",
  "total": 1000,
  "status": "ACTIVE"
}
###
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "patient_id": 1,
  "date": "2025-10-15",
  "total": 1000,
  "status": "ACTIVE"
}
###
PATCH {{baseUrl}}/orders/public/1
Content-Type: application/json

{
  "total": 1200
}
###
PATCH {{baseUrl}}/orders/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "total": 1200
}
###
DELETE {{baseUrl}}/orders/public/100
###
DELETE {{baseUrl}}/orders/1
Authorization: Bearer {{token}}
###
DELETE {{baseUrl}}/orders/public/2/logic
###
DELETE {{baseUrl}}/orders/1/logic
Authorization: Bearer {{token}}