GET http://localhost:3000/orders/public
GET http://localhost:3000/orders
Authorization: Bearer <token>

GET http://localhost:3000/orders/public/1
GET http://localhost:3000/orders/1
Authorization: Bearer <token>

POST http://localhost:3000/orders/public
Content-Type: application/json

{
  "patient_id": 1,
  "date": "2025-10-15",
  "total": 1000,
  "status": "PENDING"
}

POST http://localhost:3000/orders
Authorization: Bearer <token>
Content-Type: application/json

{
  "patient_id": 1,
  "date": "2025-10-15",
  "total": 1000,
  "status": "PENDING"
}

PATCH http://localhost:3000/orders/public/1
Content-Type: application/json

{
  "total": 1200
}

PATCH http://localhost:3000/orders/1
Authorization: Bearer <token>
Content-Type: application/json

{
  "total": 1200
}

DELETE http://localhost:3000/orders/public/1
DELETE http://localhost:3000/orders/1
Authorization: Bearer <token>

DELETE http://localhost:3000/orders/public/1/logic
DELETE http://localhost:3000/orders/1/logic
Authorization: Bearer <token>