@baseUrl = http://localhost:3000
@token = 
GET {{baseUrl}}/payments/public
###
GET {{baseUrl}}/payments
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/payments/public/2
###
GET {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/payments/public
Content-Type: application/json

{
  "order_id": 1,
  "amount": 500,
  "method": "card",
  "date": "2025-06-16 01:48:16",
  "status": "ACTIVE"
}
###
POST {{baseUrl}}/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "order_id": 1,
  "amount": 500,
  "method": "card",
  "date": "2025-06-16 01:48:16",
  "status": "ACTIVE"
}
###
PATCH {{baseUrl}}/payments/public/2
Content-Type: application/json

{
  "method": "CARD"
}
###
PATCH {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "method": "CARD"
}
###
DELETE {{baseUrl}}/payments/public/2
###
DELETE {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
###
DELETE {{baseUrl}}/payments/public/15/logic
###
DELETE {{baseUrl}}/payments/1/logic
Authorization: Bearer {{token}}