@baseUrl = http://localhost:3000
@token = 
GET {{baseUrl}}/suppliers/public
###
GET {{baseUrl}}/suppliers
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/suppliers/public/1
###
GET {{baseUrl}}/suppliers/1
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/suppliers/public
Content-Type: application/json

{
  "name": "Proveedor S.A.",
  "phone": "123456789",
  "email": "proveedor@email.com",
  "address": "Calle 123",
  "status": "ACTIVE"
}
###
POST {{baseUrl}}/suppliers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proveedor S.A.",
  "phone": "123456789",
  "email": "proveedor@email.com",
  "address": "Calle 123",
  "status": "ACTIVE"
}
###
PATCH {{baseUrl}}/suppliers/public/1
Content-Type: application/json

{
  "phone": "987654321"
}
###
PATCH {{baseUrl}}/suppliers/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "phone": "987654321"
}
###
DELETE {{baseUrl}}/suppliers/public/1
###
DELETE {{baseUrl}}/suppliers/1
Authorization: Bearer {{token}}
###
DELETE {{baseUrl}}/suppliers/public/5/logic
###
DELETE {{baseUrl}}/suppliers/1/logic
Authorization: Bearer {{token}}